name: openaccessweek2019
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - python=3.7
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - rise
  - pip
  - pip:
    - folium
    - geopy
    - sodapy
